using System;
using Moc.Domain.Common;
using Moc.Domain.Enums;

namespace Moc.Domain.Entities;

/// <summary>
/// Aggregate root representing a Management of Change (MOC) request.
/// A single entity is used for Standard EMOC, Bypass EMOC, OMOC, and DMOC via RequestType discriminator.
/// </summary>
public class MocRequest : AuditableEntity
{
    /// <summary>
    /// Human-readable control number displayed across the app and used for search.
    /// Generated by application rules (not by the UI).
    /// </summary>
    public string ControlNumber { get; set; } = string.Empty;

    /// <summary>
    /// Discriminator for request type (Standard/BYPASS/OMOC/DMOC).
    /// </summary>
    public MocRequestType RequestType { get; set; }

    /// <summary>
    /// Short title describing the change.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Originator name or user identifier. For now this remains a string until real auth is plugged in.
    /// </summary>
    public string Originator { get; set; } = string.Empty;

    /// <summary>
    /// Organizational classification for filtering/routing.
    /// </summary>
    public Guid DivisionId { get; set; }

    /// <summary>
    /// Organizational classification for filtering/routing.
    /// </summary>
    public Guid DepartmentId { get; set; }

    /// <summary>
    /// Organizational classification for filtering/routing.
    /// </summary>
    public Guid SectionId { get; set; }

    /// <summary>
    /// Category classification for filtering/reporting.
    /// </summary>
    public Guid CategoryId { get; set; }

    /// <summary>
    /// Subcategory classification for filtering/reporting.
    /// </summary>
    public Guid SubcategoryId { get; set; }

    /// <summary>
    /// Unit(s) affected; normalized later if needed. Kept as text for faster initial implementation.
    /// </summary>
    public string UnitsAffected { get; set; } = string.Empty;

    /// <summary>
    /// Equipment tag identifier used for search and traceability.
    /// </summary>
    public string EquipmentTag { get; set; } = string.Empty;

    /// <summary>
    /// Indicates whether the change is temporary. Temporary changes use restoration rules.
    /// </summary>
    public bool IsTemporary { get; set; }

    /// <summary>
    /// Target date for implementing the change; used for overdue highlighting.
    /// </summary>
    public DateTime TargetImplementationDate { get; set; }

    /// <summary>
    /// Planned restoration date for temporary changes; used to highlight overdue restoration.
    /// </summary>
    public DateTime? PlannedRestorationDate { get; set; }

    /// <summary>
    /// Scope description captured at initiation to help reviewers and approvers.
    /// </summary>
    public string ScopeDescription { get; set; } = string.Empty;

    /// <summary>
    /// Risk assessment tool label and resulting risk level (optional until the RA section is completed).
    /// </summary>
    public string? RiskToolUsed { get; set; }

    /// <summary>
    /// Risk result used for list coloring and workflow rules (e.g., auto-add PSSR).
    /// </summary>
    public RiskLevel? RiskLevel { get; set; }

    /// <summary>
    /// Current workflow stage for the request.
    /// </summary>
    public MocStage CurrentStage { get; set; } = MocStage.Initiation;

    /// <summary>
    /// Lifecycle status for segmentation and filtering.
    /// </summary>
    public MocStatus Status { get; set; } = MocStatus.Draft;

    /// <summary>
    /// For Bypass EMOC: duration in days (max 30 days per requirements). Null for non-bypass.
    /// </summary>
    public int? BypassDurationDays { get; set; }

    /// <summary>
    /// For Bypass EMOC: normal vs emergency. Null for non-bypass.
    /// </summary>
    public bool? IsBypassEmergency { get; set; }

    /// <summary>
    /// For Bypass EMOC: bypass type (free-text for now; later can become a lookup).
    /// </summary>
    public string? BypassType { get; set; }

    /// <summary>
    /// When set, indicates the request has been inactive due to no updates beyond the threshold.
    /// This supports the list highlighting and escalation logic.
    /// </summary>
    public DateTime? MarkedInactiveAtUtc { get; set; }

    /// <summary>
    /// High-level MOC classification (EMOC, DMOC, OMOC) for control number format and reporting.
    /// Additive; can be derived from RequestType when populated.
    /// </summary>
    public MocType? MocType { get; set; }

    /// <summary>
    /// Control number format components: [Type]-[Year]-[Month]-[Area]-[Category]-[Code].
    /// Year part (e.g. 2025). Null until control number is generated with structured format.
    /// </summary>
    public int? ControlNumberYear { get; set; }

    /// <summary>
    /// Control number month part (1-12). Null until control number is generated with structured format.
    /// </summary>
    public int? ControlNumberMonth { get; set; }

    /// <summary>
    /// Control number area part (e.g. division/site code). Null until structured format is used.
    /// </summary>
    public string? ControlNumberArea { get; set; }

    /// <summary>
    /// Control number category part. Null until structured format is used.
    /// </summary>
    public string? ControlNumberCategory { get; set; }

    /// <summary>
    /// Control number sequence/code part. Null until structured format is used.
    /// </summary>
    public string? ControlNumberCode { get; set; }

    /// <summary>
    /// Collection of action items under this request.
    /// </summary>
    public ICollection<MocActionItem> ActionItems { get; set; } = new List<MocActionItem>();

    /// <summary>
    /// Collection of documents (uploads/links) under this request.
    /// </summary>
    public ICollection<MocDocument> Documents { get; set; } = new List<MocDocument>();

    /// <summary>
    /// Approver chain slots for this request.
    /// </summary>
    public ICollection<MocApprover> Approvers { get; set; } = new List<MocApprover>();

    /// <summary>
    /// Activity log entries for this request (audit trail).
    /// </summary>
    public ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();
}

